### ISSUE TITLE
Map cuts itself in half when switching views

### ISSUE THREAD

**Issue by spohner** [ElinorCrew/loppemarked#3]
When switching views tha map does not behave properly. Only about half of the map is rendered.

**Comment by hgranlund** [comment]
Feilen er at lat og lng i market modelen er av type string. Dette er på grunn av at node-pg, pakken som blir brukt til å parse postgresql i sequilize, har valgt det slik. Det skal vist være forskjellige konverteringsproblemer fra decimal til float i.

For mer informasjon se [her](https://github.com/sequelize/sequelize/issues/1964)
